// 全局人物池（游戏当前在用的角色）
const characters = [
  {
    id: "sumit",
    name: "Sumit",
    type: "PI",
    photo: "game/src/photo_raw/Sumit.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 10,
    fundingGainatOfficeProbability: 0.3,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 2,
    respectGainatLectureProbability: 1,
    respectGainatBar: 0.1,
    respectGainatBarProbability: 1,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0,
    gotobarProbability: 0.01,
    special: "Great teacher",
    hired: true,
        // current map location: null when in card area
    location: null
  }
  // 其他固定角色也可以放这里
];

const phdCandidates = [
    {
    id: "Andras",
    name: "Andras",
    type: "PhD",
    photo: "game/src/photo_raw/Andras.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 0.1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.01,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Python guru",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    },  
    {
    id: "Davide",
    name: "Davide",
    type: "PhD",
    photo: "game/src/photo_raw/Davide.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 0.1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.01,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Just so so",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {   
    id: "Digvijay",
    name: "Digvijay",
    type: "PhD",
    photo: "game/src/photo_raw/Digvijay.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Camila",
    name: "Camila",
    type: "PhD",
    photo: "game/src/photo_raw/Camila.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Girl power",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Benedikt",
    name: "Benedikt",
    type: "PhD",
    photo: "game/src/photo_raw/Benedikt.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Girl power",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null},

    {
    id: "Francesca",
    name: "Francesca",
    type: "PhD",
    photo: "game/src/photo_raw/Francesca.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null},
    {
    id: "YuChih",
    name: "YuChih",
    type: "PhD",
    photo: "game/src/photo_raw/YuChih.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Ivo",
    name: "Ivo",
    type: "PhD",
    photo: "game/src/photo_raw/Ivo.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Prem",
    name: "Prem",
    type: "PhD",
    photo: "game/src/photo_raw/Prem.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Mehrdad",
    name: "Mehrdad",
    type: "PhD",
    photo: "game/src/photo_raw/Mehrdad.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Sheng",
    name: "Sheng",
    type: "PhD",
    photo: "game/src/photo_raw/Sheng.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    }
];

const postdocCandidates = [
    {
    id: "Alex",
    name: "Alex",
    type: "Postdoc",
    photo: "game/src/photo_raw/Alex.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Keep talking",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },  
    {
    id: "Ananya",
    name: "Ananya",
    type: "Postdoc",
    photo: "game/src/photo_raw/Ananya.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Yes, definitely",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Gentle",
    name: "Gentle",
    type: "Postdoc",
    photo: "game/src/photo_raw/Gentle.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Junyu",
    name: "Junyu",
    type: "Postdoc",
    photo: "game/src/photo_raw/Junyu.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Mateusz",
    name: "Mateusz",
    type: "Postdoc",
    photo: "game/src/photo_raw/Mateusz.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Safety officer",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Stefan",
    name: "Stefan",
    type: "Postdoc",
    photo: "game/src/photo_raw/Stefan.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Politician",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Slawomir",
    name: "Slawomir",
    type: "Postdoc",
    photo: "game/src/photo_raw/Slawomir.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Shayne",
    name: "Shayne",
    type: "Postdoc",
    photo: "game/src/photo_raw/Shayne.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 10,
    fundingGainatOfficeProbability: 0.3,
    fundingLossatLab: 10,
    progressGainatLab: 3,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    }
];

const coPICandidates = [
    {
    id: "Florian",
    name: "Florian",
    type: "coPI",
    photo: "game/src/photo_raw/Florian.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 10,
    fundingGainatOfficeProbability: 0.5,
    fundingLossatLab: 10,
    progressGainatLab: 2,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    },  
    {
    id: "Klaasjan",
    name: "Klaasjan",
    type: "coPI",
    photo: "game/src/photo_raw/Klaasjan.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Robert",
    name: "Robert",
    type: "coPI",
    photo: "game/src/photo_raw/Robert.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Philippe",
    name: "Philippe",
    type: "coPI",
    photo: "game/src/photo_raw/Philippe.png",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Benjamin",
    name: "Benjamin",
    type: "coPI",
    photo: "game/src/photo_raw/Benjamin.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 1,
    hired: false,
        // current map location: null when in card area
    location: null
    },
    {
    id: "Umakant",
    name: "Umakant",
    type: "coPI",
    photo: "game/src/photo_raw/Umakant.jpg",
    energy: 100,
    energyGainatDorm: 2,
    energyLossatOffice: 1,
    energyLossatLab: 1,
    energyLossatLecture: 1,
    energyGainatBar: 1,
    energyGainatBarProbability: 0.99,
    energyLossatBar: 5,
    energyLossatBarProbability: 0.01,
    fundingGainatOffice: 1,
    fundingGainatOfficeProbability: 0.1,
    fundingLossatLab: 10,
    progressGainatLab: 1,
    progressGainatLabProbability: 0.9,
    progressLossatLab: 0.1,
    progressLossatLabProbability: 0.1,
    respectGainatLecture: 1,
    respectGainatLectureProbability: 1,
    respectGainatBar: 1,
    respectGainatBarProbability: 0.99,
    respectLossatBar: 0.1,
    respectLossatBarProbability: 0.01,
    gotobarProbability: 0.01,
    special: "Great teacher",
    level: 2,
    hired: false,
        // current map location: null when in card area
    location: null
    }
];